import React, { useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import api from '../services/api';

export default function BillScreen() {
  const [bill, setBill] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/api/bills').then(({data})=>setBill(data.bill || data)).catch(()=>{}).finally(()=>setLoading(false)); },[]);
  const rows = Object.entries(bill?.maintenanceBill || {}).filter(([, value]) => typeof value === 'number').map(([name, amount]) => ({ name: name.replace(/([A-Z])/g, ' $1'), amount }));
  return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.content}>{loading ? <ActivityIndicator size="large" color="#198754"/> : <><View style={styles.actions}><TouchableOpacity style={styles.infoBtn}><Text>Download Bill</Text></TouchableOpacity><TouchableOpacity style={styles.payBtn}><Text style={styles.payText}>Pay Bill</Text></TouchableOpacity></View><View style={styles.bill}><Text style={styles.society}>{bill?.society?.societyName || 'Mayon Grand Ellora'}</Text><Text style={styles.address}>Society Maintenance Bill</Text><View style={styles.meta}><Text>Bill No: <Text style={styles.bold}>1301</Text></Text><Text>For: <Text style={styles.bold}>{bill?.month} {bill?.year}</Text></Text></View><View style={styles.meta}><Text>Name: <Text style={styles.bold}>{bill?.resident?.firstName} {bill?.resident?.lastName}</Text></Text><Text>Flat: <Text style={styles.bold}>{bill?.resident?.flatNumber}</Text></Text></View><View style={styles.tableHead}><Text style={[styles.cell,styles.sr]}>Sr.</Text><Text style={[styles.cell,styles.particular]}>Particulars</Text><Text style={[styles.cell,styles.amount]}>Amount</Text></View>{rows.map((r,index)=><View style={styles.tableRow} key={index}><Text style={[styles.cell,styles.sr]}>{index+1}</Text><Text style={[styles.cell,styles.particular]}>{r.name}</Text><Text style={[styles.cell,styles.amount]}>₹ {r.amount}</Text></View>)}<View style={styles.total}><Text style={styles.bold}>Total Amount</Text><Text style={styles.totalValue}>₹ {bill?.totalAmount || 0}</Text></View></View></>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#fff'},content:{padding:16},actions:{flexDirection:'row',justifyContent:'center',gap:10,marginBottom:20},infoBtn:{backgroundColor:'#0dcaf0',borderRadius:22,paddingHorizontal:17,paddingVertical:11},payBtn:{backgroundColor:'#198754',borderRadius:22,paddingHorizontal:20,paddingVertical:11},payText:{color:'#fff',fontWeight:'700'},bill:{borderWidth:1,borderColor:'#ddd'},society:{fontSize:20,fontWeight:'700',textAlign:'center',paddingTop:20},address:{textAlign:'center',color:'#6c757d',padding:8},meta:{flexDirection:'row',justifyContent:'space-between',padding:12,borderTopWidth:1,borderColor:'#ddd'},tableHead:{flexDirection:'row',backgroundColor:'#f1f3f5',borderTopWidth:1,borderColor:'#ddd'},tableRow:{flexDirection:'row',borderTopWidth:1,borderColor:'#ddd'},cell:{padding:11,borderRightWidth:1,borderColor:'#ddd'},sr:{width:'13%',textAlign:'center'},particular:{width:'57%'},amount:{width:'30%',textAlign:'right',borderRightWidth:0},total:{flexDirection:'row',justifyContent:'space-between',padding:14,borderTopWidth:2,borderColor:'#212529'},bold:{fontWeight:'700'},totalValue:{fontWeight:'700',color:'#198754'}});
