import React, { useContext, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { AuthContext } from '../context/AuthContext';
import api from '../services/api';

export default function NoticeboardScreen({ navigation }) {
  const { user } = useContext(AuthContext); const [notices, setNotices] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/api/notices').then(({data}) => setNotices(data.notices || [])).catch(() => {}).finally(() => setLoading(false)); }, []);
  const remove = (id) => Alert.alert('Delete notice?', 'This will remove the notice for every resident.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await api.delete(`/api/notices/${id}`); setNotices(items => items.filter(item => item._id !== id)); } catch { Alert.alert('Unable to delete notice'); } } }]);
  return <SafeAreaView style={styles.page}><FlatList data={notices} keyExtractor={(i, n) => i._id || String(n)} contentContainerStyle={styles.content}
    ListHeaderComponent={<><View style={styles.title}><Ionicons name="megaphone" color="#ffc107" size={29}/><Text style={styles.heading}>Society Noticeboard</Text><Text style={styles.subheading}>Stay updated with the latest announcements and community news.</Text></View>{user?.isAdmin && <TouchableOpacity style={styles.create} onPress={() => navigation.navigate('CreateNotice')}><Ionicons name="add-circle" size={20} color="#fff"/><Text style={styles.createText}>Create Notice</Text></TouchableOpacity>}</>}
    ListEmptyComponent={loading ? <ActivityIndicator color="#0d6efd" size="large"/> : <Text style={styles.empty}>No Notices Available</Text>}
    renderItem={({item}) => <View style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.noticeTitle}><Ionicons name="pin" size={17} color="#dc3545"/>  {item.subject || item.title}</Text><Text style={styles.date}><Ionicons name="calendar-outline" size={13}/>  {item.date || ''}</Text></View><Text style={styles.badge}>Admin</Text></View><View style={styles.rule}/><Text style={styles.details}>{item.details || item.content}</Text>{user?.isAdmin && item._id && <TouchableOpacity style={styles.delete} onPress={() => remove(item._id)}><Ionicons name="trash-outline" size={16} color="#dc3545"/><Text style={styles.deleteText}>Delete Notice</Text></TouchableOpacity>}</View>}/>
  </SafeAreaView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#f4f9f9'},content:{padding:16,gap:16},title:{alignItems:'center',paddingVertical:17},heading:{fontSize:22,fontWeight:'700',color:'#212529',marginTop:7},subheading:{color:'#6c757d',textAlign:'center',marginTop:5},create:{backgroundColor:'#0d6efd',alignSelf:'center',borderRadius:25,paddingHorizontal:20,paddingVertical:12,flexDirection:'row',gap:8,marginBottom:22},createText:{color:'#fff',fontWeight:'700'},card:{backgroundColor:'#fff',borderRadius:20,padding:22,shadowColor:'#000',shadowOpacity:.08,shadowRadius:8,elevation:3},row:{flexDirection:'row'},noticeTitle:{fontSize:17,fontWeight:'700',color:'#212529',lineHeight:24},date:{color:'#6c757d',fontSize:12,marginTop:6},badge:{alignSelf:'flex-start',backgroundColor:'#198754',color:'#fff',paddingHorizontal:9,paddingVertical:4,borderRadius:8,fontSize:12,fontWeight:'700'},rule:{height:1,backgroundColor:'#e9ecef',marginVertical:17},details:{color:'#495057',lineHeight:23},delete:{marginTop:18,alignSelf:'flex-start',flexDirection:'row',gap:6,padding:8,borderWidth:1,borderColor:'#dc3545',borderRadius:8},deleteText:{color:'#dc3545',fontWeight:'700',fontSize:12},empty:{textAlign:'center',padding:40,color:'#6c757d'}});
